pages:
  - page_name: Home
    icon: ğŸ 
    script_path: Home.py
    layout: wide  # By default, layout is 'centered' for all pages. See all the default values in page_config.py

  - page_name: Your occasion
    icon: ğŸ¥‚
    script_path: pages/Your_occasion.py
    layout: wide  # By default, layout is 'centered' for all pages. See all the default values in page_config.py

  - page_name: Your wine
    icon: ğŸ·
    script_path: pages/Your_wine.py
    layout: wide  # By default, layout is 'centered' for all pages. See all the default values in page_config.py

  - page_name: Your sommelier
    icon: ğŸ¤–
    script_path: pages/Your_sommelier.py
    layout: wide  # By default, layout is 'centered' for all pages. See all the default values in page_config.py




# sections:
#   - name: Utility Apps
#     icon: â­
#     pages:
#       - page_name: Example One
#         icon: ğŸ¤ 
#         date_added: 2022-07-04  # If younger than 30 days, the page name will be augmented with a neat :new: emoji!
#       - page_name: Custom name!  # Explicit naming here overwrites the name inferred from script_path
#         icon: âš¡
#         script_path: pages/example_two.py
#   - name: More Apps
#     icon: ğŸ’»
#     pages:
#       - page_name: Example three
#         icon: ğŸ¦‡
#       - page_name: Old App
#         icon: ğŸ’€
#         visible: false  # This app will not appear in the menu!
